### ISSUE TITLE
How about some docs?

### ISSUE THREAD

**Issue by gbirchmeier** [activerecord-hackery/polyamorous#16]
We noticed that our site is using this gem through some dependency, so I thought I'd look it up, which brought me here... where I'm learning *nothing*.

How about a couple lines of text to tell us what this gem actually does?

**Comment by radar** [comment]
Thank you for your kind and generous feedback.

Can you show us where your app is using this gem? Typically it's used only as a part of Ransack. I didn't think it was used independently from that.

**Comment by gbirchmeier** [comment]
It is, in fact, in my app because of Ransack (via ActiveAdmin).

Frankly, the name simply caught my eye.  "*Polyamorous*?  What could that be for?"  So I came here looking for the answer (and didn't find it).

**Comment by radar** [comment]
Your passive aggressive attitude has really inspired me to write some documentation this morning.

I'll get right on it.

**Comment by gbirchmeier** [comment]
I'm not asking for full docs, just 2 or 3 lines in the README to describe what this gem is for.  If it's not meant to stand alone, then maybe just a note saying so.

(PA?  I thought I was being pretty straightforward.)

**Comment by jonatack** [comment]
Done 7075e4f9e6041bf17ae9887d62d7dd8ea0974fd3.

Closing.

**Comment by jonatack** [comment]
FWIW, in the README @ernie had originally written "Move along. Nothing to see here." And I removed it a year ago or so, so it's my fault :smiling_imp: but now fixed.

**Comment by gbirchmeier** [comment]
That's perfect.  Thanks!
