### ISSUE TITLE
#left_outer_joins in Rails 5 returns INNER JOIN

### ISSUE THREAD

**Issue by neb2000** [activerecord-hackery/polyamorous#20]
`#make_left_outer_joins` in `activerecord/lib/active_record/associations/join_dependency.rb` overrides `join_type` to `Arel::Nodes::OuterJoin` (https://github.com/rails/rails/commit/e038975), whereas `#make_polyamorous_left_outer_joins` in `activerecord_5.0_ruby_2/join_dependency.rb` does the following:

```ruby
join_type = child.join_type || Arel::Nodes::OuterJoin
```

When doing a `#left_outer_joins`, `child` comes in with the join_type `Arel::Nodes::InnerJoin`, which as a result when polyamorous is installed, `#left_outer_joins` in ActiveRecord 5 always perform an INNER JOIN.

**Comment by jonatack** [comment]
Addressed by #21.
