### ISSUE TITLE
Rails 5.2 alpha

### ISSUE THREAD

**Issue by halo** [activerecord-hackery/polyamorous#26]
I'm trying out edge Rails 5.2 alpha in a project that uses ransack. So this line fails:

https://github.com/activerecord-hackery/polyamorous/blob/2e4a587d4f3a8b074f2ee556781e94d835e15220/lib/polyamorous.rb#L41

```ruby
cannot load such file -- polyamorous/activerecord_5.2_ruby_2/join_association (LoadError)
```

What's your take on this? Should I just create those files? Copy paste the older ones? Should the conditional learn to simply load the latest version if none applicable can be found?

Thank you for your time!

**Comment by halo** [comment]
Alas! A new argument [was introduced here](https://github.com/rails/rails/commit/ea09bf5419ec752dd020d26b03533afa457d09d6) so this cannot be done the quick and easy way.

**Comment by Romulla** [comment]
Hi, I've got the same issue. If not quick and easy way exists, what would be the slow and difficult way? Can I downgrade to keep functionality in the dependence chain?

**Comment by starknx** [comment]
gem 'ransack'
gem 'polyamorous', github: 'starknx/polyamorous'

**Comment by Petercopter** [comment]
Ransack here as well, same error. In Rails Beta 2.

**Comment by obie** [comment]
Same issue, ransack via ActiveAdmin

**Comment by bragboy** [comment]
Any updates or workarounds ?

**Comment by ribanez7** [comment]
Is there anyone working on this? Same problem here.

**Comment by bbonislawski** [comment]
This works for me at the moment: 
https://github.com/spark-solutions/polyamorous/

**Comment by varyonic** [comment]
Same as activerecord-hackery/polyamorous#29

**Comment by Petercopter** [comment]
@bbonislawski With Rails 5.2beta and your fork loaded, I'm getting
```
ArgumentError:
        wrong number of arguments (given 3, expected 4)
```
from something that looks like
```
@q = Model.search(params)
```

**Comment by halo** [comment]
@Petercopter The error you're experiencing is from the ransack gem itself, see https://github.com/activerecord-hackery/ransack/issues/849

There are a number of issues and pull requests in both repos related to this, it's kinda hard to keep track of it :)

**Comment by bbonislawski** [comment]
@Petercopter I forgot about ransack. I've updated it too for myself:
https://github.com/spark-solutions/ransack

**Comment by Petercopter** [comment]
@halo Thanks for the info!
@bbonislawski I'm using the forked Ransack and Polyamorous now. I should have mentioned that the application would not boot before your Polyamorous changes. Now that I've the Ransack fork loaded as well, I'm running the full test suite. There is a forest of deprecation errors that I need to work on, but also...

The first thing I'm seeing is this:
```
@count = @search.result.count
ActiveRecord::EagerLoadPolymorphicError:
  Cannot eagerly load the polymorphic association :series
```

This association is not polymorphic, its `Title -> belongs_to -> Season -> belongs_to -> Series`.

**Comment by bbonislawski** [comment]
@Petercopter I'm looking into that. Thanks for reporting the issue

**Comment by bbonislawski** [comment]
@Petercopter can you provide more details on your issue? I've tried to reproduce issue locally but didn't success. Can you provide whole stacktrace and more details about code?

**Comment by Petercopter** [comment]
@bbonislawski 
Using polyamorous 1.3.1 from https://github.com/spark-solutions/polyamorous (at master@d02fc35)
Using ransack 1.8.4 from https://github.com/spark-solutions/ransack (at master@b8b982c)

Let me know what else you need, I'm really happy to be helping.

```
2) Sort links data-filter should submit form if clicking a data-filter link
Failure/Error: @count = @search.result.reorder('').except(:select).count

ActiveRecord::StatementInvalid:
  PG::DuplicateAlias: ERROR:  table name "series" specified more than once
  : SELECT COUNT(DISTINCT "titles"."id") FROM "titles" LEFT OUTER JOIN "seasons" ON "seasons"."id" = "titles"."season_id" INNER JOIN "series" ON "series"."id" = "seasons"."series_id" LEFT OUTER JOIN "customers" ON "customers"."id" = "titles"."customer_id" LEFT OUTER JOIN "customers" "billing_customers_titles" ON "billing_customers_titles"."id" = "titles"."billing_customer_id" LEFT OUTER JOIN "notes" ON "notes"."notable_id" = "titles"."id" AND "notes"."notable_type" = $1 AND "notes"."category" = $2 LEFT OUTER JOIN "languages" ON "languages"."id" = "titles"."language_id" LEFT OUTER JOIN "title_versions" ON "title_versions"."child_id" = "titles"."id" LEFT OUTER JOIN "platform_types" ON "platform_types"."id" = "titles"."platform_type_id" LEFT OUTER JOIN "portals" ON "portals"."id" = "titles"."portal_id" LEFT OUTER JOIN "priorities" ON "priorities"."id" = "titles"."priority_id" LEFT OUTER JOIN "purchase_orders" ON "purchase_orders"."id" = "titles"."purchase_order_id" LEFT OUTER JOIN "seasons" "seasons_titles" ON "seasons_titles"."id" = "titles"."season_id" LEFT OUTER JOIN "series" ON "series"."id" = "seasons"."series_id" LEFT OUTER JOIN "sla_types" ON "sla_types"."id" = "titles"."sla_type_id" LEFT OUTER JOIN "statuses" ON "statuses"."id" = "titles"."status_id" LEFT OUTER JOIN "icons" ON "icons"."id" = "statuses"."icon_id" LEFT OUTER JOIN "studios" ON "studios"."id" = "titles"."studio_id" LEFT OUTER JOIN "distributors" ON "distributors"."id" = "studios"."distributor_id" LEFT OUTER JOIN "title_edition_types" ON "title_edition_types"."id" = "titles"."title_edition_type_id" LEFT OUTER JOIN "users" ON "users"."id" = "titles"."user_id" LEFT OUTER JOIN "title_tags" ON "title_tags"."title_id" = "titles"."id" LEFT OUTER JOIN "tags" ON "tags"."id" = "title_tags"."tag_id" LEFT OUTER JOIN "workflows" ON "workflows"."id" = "titles"."workflow_id" WHERE (titles.status_id <> 1854) AND (titles.status_id <> 1858) AND "titles"."restriction_type" = $3
# ./app/controllers/concerns/titles/search_concern.rb:15:in `set_count'
# /home/rof/cache/bundler/ruby/2.4.0/gems/audited-4.5.0/lib/audited/sweeper.rb:14:in `around'
# /home/rof/cache/bundler/ruby/2.4.0/gems/audited-4.5.0/lib/audited/sweeper.rb:14:in `around'
# /home/rof/cache/bundler/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
# /home/rof/cache/bundler/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/rack/logger.rb:38:in `call_app'
# /home/rof/cache/bundler/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/rack/logger.rb:28:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/request_store-1.3.2/lib/request_store/middleware.rb:9:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/deflater.rb:34:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/railties-5.2.0.beta2/lib/rails/engine.rb:524:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/capybara-2.16.1/lib/capybara/server.rb:44:in `call'
# /home/rof/cache/bundler/ruby/2.4.0/gems/rack-2.0.3/lib/rack/handler/webrick.rb:86:in `service'
# ------------------
# --- Caused by: ---
# PG::DuplicateAlias:
#   ERROR:  table name "series" specified more than once
#   ./app/controllers/concerns/titles/search_concern.rb:15:in `set_count'
```

**Comment by bbonislawski** [comment]
@seanfcarroll I guess issue is not fixed. Code from my PR was working and with current version 1.3.2 I get tons of errors https://circleci.com/gh/spark-solutions/spree/2582?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack

**Comment by halo** [comment]
@bbonislawski From your link to circle ci it's not entirely clear whether the error stems from the `polyamorous` gem or the `ransack` gem. 

Or do I understand you correctly that https://github.com/activerecord-hackery/polyamorous/pull/28 does not work for you but https://github.com/activerecord-hackery/polyamorous/pull/29 does?

If so, where is the difference? And can you provide a PR to fix that? That PR should include at least one failing spec scenario so it becomes clear that this is fixed. 

This has been requested [in this comment](https://github.com/activerecord-hackery/polyamorous/pull/28#issuecomment-351972435) but I can't find a response to that request. This has been merged to speed up the process in every way possible.

**Comment by Liooo** [comment]
Had the same problem and updating ransack to 1.8.8 fixed the issue.

Probably because it updates polyamorous gem internally used.
https://github.com/activeadmin/activeadmin/issues/5254#issuecomment-359927255

**Comment by Liooo** [comment]
Had the same problem and updating ransack to 1.8.8 fixed the issue.

Probably because it updates polyamorous gem internally used.
https://github.com/activeadmin/activeadmin/issues/5254#issuecomment-359927255
