### ISSUE TITLE
Rails master (6.0) compactability

### ISSUE THREAD

**Issue by swordray** [activerecord-hackery/polyamorous#40]
I'm trying to use features in Rails master branch (currently 6.0). Got 
```
cannot load such file -- polyamorous/activerecord_6.0_ruby_2/join_association (LoadError)
```
With activerecord_5.2_ruby_2 got 
```
activerecord/lib/active_record/associations/join_dependency/join_association.rb:12:in 'initialize': wrong number of arguments (given 3, expected 2)
```
Please help me to update this code.

**Comment by gregmolnar** [comment]
@swordray there are some breaking changes on Rails master which I am planning to fix, but we are using internal APIs which might change so it is probably wiser to wait till the RC is out at least.

**Comment by gregmolnar** [comment]
This is fixed by https://github.com/activerecord-hackery/ransack/pull/938 on ransack master.
