### ISSUE TITLE
Rails 5.2.1.rc1 is giving 'wrong number of arguments (given 3, expected 2)'

### ISSUE THREAD

**Issue by jpawlyn** [activerecord-hackery/polyamorous#41]
Hi. I am getting the error for `has_many` associations with a `through` argument. It looks as if [this Rails commit](https://github.com/rails/rails/commit/15e3e9cdccd8ab0d204ed9e74bf7916d6025d405) added an extra argument `alias_tracker` to the method `ActiveRecord::Associations::JoinDependency#join_constraints` and this is perhaps causing the above error? 

Gem version: 1.3.3
Ruby version: 2.5.0

**Comment by gregmolnar** [comment]
@jpawlyn Polyamorous is no longer supported. We absorbed the needed bits into ransack. Do you have this issue in an app using ransack?

**Comment by jpawlyn** [comment]
@gregmolnar That's right, activeadmin (1.3.0). Any suggestion what I can do to resolve the problem? Thanks

**Comment by gregmolnar** [comment]
Point it to ransack master, there is a WIP PR(https://github.com/activerecord-hackery/ransack/pull/938) to make it work with Rails 5.2.1, so it should be sorted soon.
