### ISSUE TITLE
Polyamorous not working with rails 5.2.1 due to join_dependency's interface changes

### ISSUE THREAD

**Issue by fursich** [activerecord-hackery/polyamorous#44]
Hi, thanks for maintaining this awesome piece! 😃 

I came here, since it looks like polyamorous (specifically ActiveRecord join) is not working with Rails > 5.2.0  (confirmed it with 5-2-stable and 5.2.1)

Here's what I came up with after digging it a little further.

## reproduction case

Let's say Item belongs to Category:

with rails 5.2.1,

```ruby
pry(main)> Item.joins(:Category).first
ArgumentError: wrong number of arguments (given 3, expected 2)
from /Users/rails/my_rails_project/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.1/lib/active_record/associations/join_dependency/join_association.rb:12:in `initialize'
```

Not only `initialize` fails, but some other methods could fail depending on queries.

With rails 5.2.0 or earlier,

```ruby
pry(main)> Item.joins(:Category).first
[DEBUG]   Item Load (5.4ms)  SELECT  `items`.* FROM `items` INNER JOIN `categories` ON `categories`.`id` = `items`.`category_id` LIMIT 1
=> #<Category:0x00007fd721a71a20
 id: 1
# ...snip
```

simply returns joined records (no surprise)

FYI, I'm using ransack (1.8.8) over polyamorous (1.3.3).

## quick investigations..

(As seen in the error messages) there are mismatches in the number of arguments in some methods related with `join_dependency` between latest rails and polyamorous that overrides them.

Examples are: [here (polyamorous)](https://github.com/activerecord-hackery/polyamorous/blob/master/lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb#L58-L76) and [here (latest ActiveRecord) ](https://github.com/rails/rails/blob/fc5dd0b85189811062c85520fd70de8389b55aeb/activerecord/lib/active_record/associations/join_dependency.rb#L79-L93)

The background of this change is briefly explained [here](https://github.com/rails/rails/commit/50036e673b3b6ff41476814b212b55fabac3a638) - apparently have been merged very recently.

As Rails 5.2.1 has just been released (and I personally need to update a rails app to the latest version), it would be really great if we get the fix for it.

In case PR is needed, I'm very happy to give it a try (wondering if somebody is already working on that..?)

Anyway, thanks a lot for maintaining this gem!

**Comment by gregmolnar** [comment]
@fursich Could you please check with master?

**Comment by fursich** [comment]
@gregmolnar 
A big thanks for your amazingly swift answer :)

I realized the job is already done with [this PR](https://github.com/activerecord-hackery/ransack/commit/5b300a839a53761699ae3f579c5acab62bbc9444
)
(sorry I came here straight after checking the error message)

Let me see how it goes with the latest master (will close the issue if everything's cool)
Thanks really a lot for saving my day 🙏

**Comment by fursich** [comment]
Looks like it's working well.
Let me close this issue right away. Thanks a lot again, @gregmolnar

**Comment by mattwr18** [comment]
Thanks for opening this issue @fursich, just ran into this and it saved me potentially a lot of time.
