### ISSUE TITLE
What about BabySqueel?

### ISSUE THREAD

**Issue by brandonzylstra** [activerecord-hackery/polyamorous#47]
> Polyamorous is merged into Ransack since Squeel and MetaSearch is not maintained anymore

the idea that is unstated but apparently implied is that there is no longer any value in maintaining this as an independent gem, because _nothing at all is using it anymore except Ransack_.  But the problem is that that's not true.  In the very least [BabySqueel is using it](https://github.com/rzane/baby_squeel/blob/master/baby_squeel.gemspec).  Would you consider keeping polyamorous separate going as a separate gem?

**Comment by gregmolnar** [comment]
@brandondrew Honestly, it caused more issues than helped to keep polyamorous separated. When there is a bug, it is hard to locate where the exact issue is, you need to maintain the releases for both gems etc. So I would say no, there is no interest from me to maintain this gem as well. But feel free to backport any changes from the ransack repo, I will try to review and merge them.
