### ISSUE TITLE
Not compatible with rails 5.2.1

### ISSUE THREAD

**Issue by kelso** [activerecord-hackery/polyamorous#48]
Upgraded to 5.2.1 from 5.2.0 and I get this error:

```
ArgumentError: wrong number of arguments (given 3, expected 2)
from /Users/xxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/polyamorous-1.3.3/lib/polyamorous/activerecord_5.2_ruby_2/join_dependency.rb:58:in `join_constraints'
```

I've just found out this method really defines only 2 arguments

```
def join_constraints(outer_joins, join_type)
```

but new rails 5.2.1 defines it with 3 arguments:

```
def join_constraints(joins_to_add, join_type, alias_tracker)
```

Please see [rails source code join_dependency.rb:79](https://github.com/rails/rails/blob/v5.2.1/activerecord/lib/active_record/associations/join_dependency.rb#L79)

**Comment by gregmolnar** [comment]
Please upgrade ransack to 2.0.0
