### ISSUE TITLE
Joins on has_many associations raises ArgumentError for ActiveRecord 5.2.1

### ISSUE THREAD

**Issue by jesusabarca** [activerecord-hackery/polyamorous#50]
Joining two models that have a `has_many` association raises an `ArgumentError`.

If we have this two models:

```ruby
class Article < ApplicationRecord
  belongs_to :author
end

class Author < ApplicationRecord
  has_many :articles
end
```

Running `Article.joins(:author).to_sql` raises a:
```ruby
ArgumentError: wrong number of arguments (given 3, expected 2)
```

That's because ActiveRecord's `Associations::JoinDependency::JoinAssociation` class initializer changed in Rails 5.2.1 from:
```ruby
def initialize(reflection, children, alias_tracker)
  ...
end
```
```ruby
def initialize(reflection, children)
  ...
end
```

I don't know this codebase well enough but looking at the backtrace, seems to me that the class `Polyamorous::JoinDependencyExtensions` for ActiveRecord 5.2 needs an update.

This only happens in Rails 5.2.1, version 5.2.0 works fine :)

**Comment by gregmolnar** [comment]
Use the latest ransack gem with rails 5.2 please.
