### ISSUE TITLE
error running in rails 5.2.2

### ISSUE THREAD

**Issue by Lupeipei** [activerecord-hackery/polyamorous#53]
#### version:
rails 5.2.2, ruby 2.4.1.
#### errors:
when I run `rake db:create`, error  raise:
```
cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association (LoadError)
```
I have found that the issue  [#28](https://github.com/activerecord-hackery/polyamorous/pull/28) is very similar to this one. I have also reviewed the PR [add support to rails5.2](https://github.com/activerecord-hackery/polyamorous/commit/577e79a97275a057693a6357c92925a85c026f31)  made by @gssbzn ,  he has fixed it. so I have no idea why I got the error in rails 5.2.2. It is possible that a new PR needed to support to rails 5.2.2?

**Comment by gregmolnar** [comment]
@Lupeipei with Rails 5.2.2 you should use ransack 2.1.1

**Comment by Lupeipei** [comment]
got it! Thanks!
